//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ttypes.TUnit = {
  'UNIT' : 0,
  'UNIT_PER_SECOND' : 1,
  'CPU_TICKS' : 2,
  'BYTES' : 3,
  'BYTES_PER_SECOND' : 4,
  'TIME_NS' : 5,
  'DOUBLE_VALUE' : 6,
  'NONE' : 7,
  'TIME_MS' : 8,
  'TIME_S' : 9,
  'TIME_US' : 10,
  'BASIS_POINTS' : 11
};
ttypes.TMetricKind = {
  'GAUGE' : 0,
  'COUNTER' : 1,
  'PROPERTY' : 2,
  'STATS' : 3,
  'SET' : 4,
  'HISTOGRAM' : 5
};
